### PR TITLE
Add dev_users, its members, and its associated policies

### PR DESCRIPTION
**Pull request by eddierubeiz**
Ref #6 

- "aws_iam_group" "dev_users"
  - "aws_iam_group_membership" "dev_users_membership"
    - "aws_iam_user" "eddie_dev"
    - "aws_iam_user" "jrochkind_dev"
- "aws_iam_policy" "mediaconvert_dev"
  - "aws_iam_group_policy_attachment" "dev_users_mediaconvert_dev"
- "aws_iam_policy" "read_backups"
  - "aws_iam_group_policy_attachment" "dev_users_read_backups"
- "aws_iam_policy" "read_production"
  - "aws_iam_group_policy_attachment" "dev_users_read_production"
- "aws_iam_policy" "write_dev"
  - "aws_iam_group_policy_attachment" "dev_users_write_dev"
- "aws_iam_policy" "write_staging"
  - "aws_iam_group_policy_attachment" "dev_users_write_staging"

### CODE REVIEW

**Comment by eddierubeiz** [comment]
Note: these items, obviously, already exist in AWS.

To alert Terraform that this is the case (so it doesn't attempt to create them), you need to run the following `terraform import` statements:

```
terraform import aws_iam_group.dev_users dev_users
terraform import aws_iam_user.eddie_dev eddie_dev
terraform import aws_iam_user.jrochkind_dev jrochkind_dev

terraform import aws_iam_policy.mediaconvert_dev         arn:aws:iam::335460257737:policy/mediaconvert_dev
terraform import aws_iam_policy.read_backups             arn:aws:iam::335460257737:policy/read_backups
terraform import aws_iam_policy.read_production          arn:aws:iam::335460257737:policy/read_production
terraform import aws_iam_policy.write_dev			     arn:aws:iam::335460257737:policy/write_dev
terraform import aws_iam_policy.write_staging            arn:aws:iam::335460257737:policy/write_staging
terraform import aws_iam_policy.AmazonEC2ReadOnlyAccess  arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

terraform import aws_iam_group_policy_attachment.dev_users_mediaconvert_dev         dev_users/arn:aws:iam::335460257737:policy/mediaconvert_dev
terraform import aws_iam_group_policy_attachment.dev_users_read_backups             dev_users/arn:aws:iam::335460257737:policy/read_backups
terraform import aws_iam_group_policy_attachment.dev_users_read_production          dev_users/arn:aws:iam::335460257737:policy/read_production
terraform import aws_iam_group_policy_attachment.dev_users_write_dev                dev_users/arn:aws:iam::335460257737:policy/write_dev
terraform import aws_iam_group_policy_attachment.dev_users_write_staging    		dev_users/arn:aws:iam::335460257737:policy/write_staging
terraform import aws_iam_group_policy_attachment.dev_users_AmazonEC2ReadOnlyAccess  dev_users/arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
```

And to reverse the above and remove the items from Terraform state (which means you don't want Terraform to manage them), you can run:
```
terraform state rm aws_iam_group.dev_users
terraform state rm aws_iam_user.eddie_dev
terraform state rm aws_iam_user.jrochkind_dev

terraform state rm aws_iam_group_policy_attachment.dev_users_mediaconvert_dev
terraform state rm aws_iam_group_policy_attachment.dev_users_read_backups
terraform state rm aws_iam_group_policy_attachment.dev_users_read_production
terraform state rm aws_iam_group_policy_attachment.dev_users_write_dev
terraform state rm aws_iam_group_policy_attachment.dev_users_write_staging
terraform state rm aws_iam_group_policy_attachment.dev_users_AmazonEC2ReadOnlyAccess

terraform state rm aws_iam_policy.mediaconvert_dev
terraform state rm aws_iam_policy.read_backups
terraform state rm aws_iam_policy.read_production
terraform state rm aws_iam_policy.write_dev
terraform state rm aws_iam_policy.write_staging
terraform state rm aws_iam_policy.AmazonEC2ReadOnlyAccess
```

**Comment by jrochkind** [comment]
STill a bit confusing, but I think that's the nature of the beast. I am approving, I'll let you merge @eddierubeiz  as maybe there's workflow that has to go with merging, like running on prod? Not sure!

**Review by jrochkind — APPROVED** [review]

**Comment by eddierubeiz** [comment]
- First I merged the PR,
- then I ran the above `terraform import` statements in staging
- then I ran `terraform apply` in staging
- then I ran the above `terraform import` statements in production
- then I ran `terraform apply` in production.

Great. Now `terraform apply` returns `No changes` in both staging and prod.

**Comment by jrochkind** [comment]
@eddierubeiz Sweet thanks for documenting!

I wonder if we should have a documented process for terraform stuff where we apply it fully to staging (from a branch) _before_  merging?  Like do we really know it's going to work until we've done that? Then once verified, merge and apply to production?

**Comment by eddierubeiz** [comment]
This turns out to be tricky in the case of items that already exist in AWS and are being retroactively added into Terraform state. I haven't really discovered (or rediscovered) a reliable workflow for this yet. Avenues for further research!

**Pull request merged**
