### PR TITLE
Add server side encryption configuration stanzas to match new configuration added by AWS

### PR DESCRIPTION
**Pull request by eddierubeiz**
AWS now encrypts all new files added to all buckets by default, and updated the configuration in all the buckets.
We're now adding a `server_side_encryption_configuration` stanza to every bucket, to match what it is in real life.
With these changes we are now once again at:
`No changes. Your infrastructure matches the configuration.`
Ref #26

### CODE REVIEW

**Comment by jrochkind** [comment]
Huh, did something change in the terraform AWS adapter or something, such that it now wants/creates these? 

If they are left out, do we just get default behavior (no encryption!) that's what we want though?  What is the problem with things as they are now that requires this change?

**Comment by jrochkind** [comment]
```
            apply_server_side_encryption_by_default {
                sse_algorithm = "AES256"
            }
```

So wait, right now we ARE using "server-side encryption"? I had no idea.  Or am I interpreting this wrong?  Is this the default or something?   We dont' need to keep track of a key or anything for "server-side encryption"?  

I think we need more info, perhaps in comments or in the README, about this feature, if this is going to be in there!

**Comment by eddierubeiz** [comment]
You're absolutely right -- the default behavior changed from not encrypted to encrypted. The relevant info is in the github issue and I'll add a comment to the README.

**Comment by jrochkind** [comment]
I wonder if we updated to latest version of terraform aws plugin, if it wouldn't insist on adding the new default to the config? I wonder if it's worth adding that yak to shave? It's probably been a while, we're probably using a fairly old vereison of terraform and terraform aws right now.

**Comment by eddierubeiz** [comment]
That's a separate yak but we can shave it anytime:
https://github.com/sciencehistory/terraform_scihist_digicoll/issues/28

**Review by jrochkind — APPROVED** [review]

**Pull request merged**
