### PR TITLE
create a separate VIDEO originals bucket (and in production, a video-originals-backup bucket)

### PR DESCRIPTION
**Pull request by jrochkind**
Created by copy-pasting the basic originals bucket definitions and changing names

Ref https://github.com/sciencehistory/scihist_digicoll/issues/1575

### CODE REVIEW

**Comment by jrochkind** [comment]
This has already been applied in both staging and production. (had a bit of trouble getting it to work). 

Also ended up fixing/refactoring existing code slightly here. 

I am trying to manually verify the replication rules are working and things will be automatically replicated to the backup bucket, but still waiting for the automatic replication to happen.

**Comment by jrochkind** [comment]
@eddierubeiz replication to backup bucket doesn't seem to actually be working, things I added to it yesterday are still not replicated. :(

**Comment by jrochkind** [comment]
Aha, the `S3-Backup-Replication` IAM *role* probably needs to be edited to have this permission. It's done in a kind of weird way. (and not via terraform).

**Comment by eddierubeiz** [comment]
That said -- and whatever the cause -- the replication failed silently?

**Comment by jrochkind** [comment]
OK after fixing permissions as above -- verified a replication working/happening! So moving this out of "draft" again.

**Pull request merged**
